version: '3.8'
services:
  mongo:
    image: mongo:6
    expose:
      - '27017'
    environment:
      MONGO_INITDB_DATABASE: gamified-goal-tracker-test

  backend-test:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/gamified-goal-tracker-test
      - PORT=5000
      - NODE_OPTIONS=--experimental-vm-modules
    depends_on:
      - mongo
    command: sh -c "npm install && npm test"

  frontend-test:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true
    command: sh -c "npm install && npm test"
